=== MrCorncrake/movie-miner/schema.JSON
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/Body",
    "definitions": {
        "Body": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "authors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "characters": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "scenes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Scene"
                    }
                }
            },
            "required": [
                "authors",
                "characters",
                "name",
                "scenes"
            ],
            "title": "Body"
        },
        "Scene": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "integer"
                },
                "transition": {
                    "type": "string"
                },
                "locations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Location"
                    }
                }
            },
            "required": [
                "id",
                "locations",
                "transition"
            ],
            "title": "Scene"
        },
        "Location": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "position": {
                    "type": "string"
                },
                "place": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "shots": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Shot"
                    }
                }
            },
            "required": [
                "place",
                "position",
                "shots",
                "time"
            ],
            "title": "Location"
        },
        "Shot": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "integer"
                },
                "on": {
                    "type": "string"
                },
                "desc": {
                    "type": "string"
                },
                "sentences": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Sentence"
                    }
                },
                "key_words": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": [
                "desc",
                "id",
                "key_words",
                "on",
                "sentences"
            ],
            "title": "Shot"
        },
        "Sentence": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "shot_id": {
                    "type": "integer"
                },
                "character": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "desc": {
                    "type": "string"
                },
                "line": {
                    "type": "string"
                }
            },
            "required": [
                "character",
                "desc",
                "line",
                "notes",
                "shot_id"
            ],
            "title": "Sentence"
        }
    }
}

=== MrCorncrake/movie-miner/rush_hour.json
{"name":"RUSH HOUR","authors":["Ross LaManna","Jim Kouf"],"characters":[],"scenes":[{"id":1,"transition":"FADE IN:","locations":[{"position":"EXT","place":"HONG KONG","time":"NIGHT","shots":[{"id":0,"on":"LOCATION","desc":"We're in a HELICOPTER POV flying over Hong Kong's dazzling skyline. SUPER - HONG KONG - JUNE 30, 1997 FADE UP the sound of a RADIO NEWSCAST as we continue to fly over luxury, high rise condos, gleaming corporate headquarters, and busy freeways.","sentences":[{"shot_id":0,"character":"NEWS ANNOUNCER","line":"(British accent) ...and now, in something less than  three hours, what was once known as  the Asian pearl of the British Empire  will revert forever to The People's  Republic of China... Suddenly, we break out of the lights of the city and FLY LOW over the dark harbor. The newscaster's voice blends with the WHUMP WHUMP of the chopper. ","followup":"Suddenly, we break out of the lights of the city and FLY LOW over the dark harbor. The newscaster's voice blends with the WHUMP WHUMP of the chopper. "}],"key_words":["JUNE","SUPER","FADE UP","WHUMP WHUMP","NEWS ANNOUNCER","HELICOPTER POV","RADIO NEWSCAST","HONG KONG","FLY LOW"]}]}]},{"id":3,"transition":"CUT TO:","locations":[{"position":"INT","place":"A WAREHOUSE","time":"NIGHT","shots":[{"id":0,"on":"LOCATION","desc":"We're CLOSE on a huge gleaming DRAGON made of tin. The dragon seems to float effortlessly across a concrete warehouse floor. PULL BACK until we see that it's riding on a fork lift toward a SHIP docked at the warehouse. As the dragon moves, we see it pass PRICELESS CHINESE ART OBJECTS including ceramics, glass paintings, and huge statues. CHINESE MEN move quickly as they load this precious cargo into the hold of the ship. ","sentences":[],"key_words":["PULL BACK","PRICELESS CHINESE ART OBJECTS","DRAGON","SHIP","CLOSE","CHINESE MEN"]}]},{"position":"INT","place":"THE HOLD","time":"NIGHT","shots":[{"id":0,"on":"LOCATION","desc":"The dragon is now descending right on top of us as it's lowered by A CRANE. A Chinese man carrying an AUTOMATIC WEAPON looks up at the dragon as he walks by. We hold on the dragon. Suddenly, A MAN'S FACE appears in the dragon's mouth. This is LEE, dressed all in black. He dives head first out of the dragon and lands silently on the deck. WHACK! A foot kicks him off the ladder and the ship. SPLASH.\r\n","sentences":[],"key_words":["WHACK","SPLASH","MAN'S FACE","AUTOMATIC WEAPON","LEE","CRANE"]},{"id":1,"on":"ON TWO GUARDS","desc":"Lee dispatches them with a FLURRY OF HANDS. SPLASH, SPLASH.\r\n","sentences":[],"key_words":["FLURRY OF HANDS","SPLASH"]},{"id":2,"on":"ON THE BOSS","desc":"A handsome Chinese man named SANG stands at the railing watching the loading process. He SHOUTS in MANDARIN and people jump to his command. Then something catches his eye. CLOSE ON The top of the warehouse. We see another man's FACE peer over the edge. And then disappear again.\r\n","sentences":[],"key_words":["SANG","SHOUTS","MANDARIN","FACE","CLOSE ON"]},{"id":3,"on":"ON THE WAREHOUSE","desc":"Ten HONG KONG COPS, weapons at the ready, are spread out on the roof watching the loading action.\r\n","sentences":[],"key_words":["HONG KONG COPS"]},{"id":4,"on":"ON SANG","desc":"He turns and sees A HELICOPTER in the distance bearing down on the boat. Without showing any panic, Sang steps inside his ship office. He runs to his desk and grabs a REBREATHER MASK from a drawer. He looks up suddenly and sees Lee standing in the doorway. Sang doesn't move a muscle as the two men stare at each other. Suddenly AUTOMATIC GUNFIRE erupts everywhere as the raid beings. Sang dives for a Berretta taped under his desk. He grabs it and starts firing. Lee rolls across the office dodging bullets. Sang runs out and down a flight of steps. Lee follows on his heels. ","sentences":[],"key_words":["AUTOMATIC GUNFIRE","HELICOPTER","REBREATHER MASK"]}]},{"position":"EXT","place":"THE SHIP","time":"NIGHT","shots":[{"id":0,"on":"LOCATION","desc":"A battle is in full progress as the Cops fire down on the bad guys. The helicopter joins the fray. We see a machine gun spray the warehouse from the chopper's open door. ","sentences":[],"key_words":[]}]},{"position":"INT","place":"THE BOAT","time":"NIGHT","shots":[{"id":0,"on":"LOCATION","desc":"Sang runs down another flight of steps, deeper in the bowels of the ship. He stops for an instant and fits the REBREATHER MASK over his face. Then he turns and fires four rounds at Lee who has to dive back in another passageway. ","sentences":[],"key_words":["REBREATHER MASK"]}]},{"position":"EXT","place":"DECK","time":"NIGHT","shots":[{"id":0,"on":"LOCATION","desc":"Lee runs up on deck as the battle is ending. Police arrest dozens of bad guys. But Lee looks out at the water where one bad guy got away. ","sentences":[],"key_words":[]}]}]},{"id":4,"transition":"CUT TO:","locations":[{"position":"EXT","place":"HAN'S RESIDENCE","time":"NIGHT","shots":[{"id":0,"on":"LOCATION","desc":"We're in a LARGE ORIENTAL GARDEN for a black tie dinner. Tuxedos and gowns. An assortment of worldly players. HAN, a handsome charismatic man is the focus of attention. He and his wife CHI-YING are at one of the tables. THOMAS GRIFFIN, 50, British, but warm and personable, has the floor.  He is at Han's table, holding up a glass of bubbly.","sentences":[{"shot_id":0,"character":"GRIFFIN","line":"-- because in my heart, I look upon it  as a tragedy. Yes, ladies and  gentlemen, a tragedy.  (to Han) Forgive me, my friend. But I believe  Hong Kong cannot afford to lose men of  your character. It's understandable  that China has envisioned a new role  for you in the United States. But  those of us here in law enforcement,  can only look upon your leave-taking  with sadness. And speaking personally,  I will sorely miss your unbridled  support of British Hong Kong Police.   So, for all us Brits who ever carried  a shield in Hong Kong...  (lifts his glass) We will miss you, but we wish you  nothing but happiness in America. The glasses clink. Lee, now dressed in a tuxedo, suddenly appears at Han's side. He whispers something in his ear. Han stands, glass in hand.","followup":"Han's side. He whispers something in his ear. Han stands, glass in hand."},{"shot_id":0,"character":"HAN","line":"(to Griffin) Tom, thank you. Very much.  (to the group) I am pleased to be able to leave you  and Hong Kong with a gift tonight:  less than an hour ago, Detective Lee Everyone drinks.\r\n","followup":"Everyone drinks.\r\n"}],"key_words":["YING","THOMAS GRIFFIN","HAN","CHI","LARGE ORIENTAL GARDEN","GRIFFIN"]},{"id":1,"on":"ON LEE","desc":"He's walking back up to the house when he senses someone behind him.  He turns and receives a fist to the stomach. SOON YOUNG, Han's daughter is pissed.","sentences":[{"shot_id":1,"character":"SOON YOUNG","line":"When were you going to tell me you  were not going with us?","followup":""},{"shot_id":1,"character":"LEE","line":"I still have work to do here.","followup":""},{"shot_id":1,"character":"SOON YOUNG","line":"I don't believe you. My father was  explaining to Mr. Griffin. That is  how I found out.","followup":""},{"shot_id":1,"character":"LEE","line":"I was trying to find the right time.","followup":""},{"shot_id":1,"character":"SOON YOUNG","line":"After I left? And she throws another punch at him. But he catches her hand. And holds it tightly, to keep from being hit again.","followup":""},{"shot_id":1,"character":"LEE","line":"I am going to miss you very much, Soon  Young. If I ever have a daughter, I  hope she is like you. Soon Young yanks her hand away from him. She glares at  him for a moment, then --","followup":""},{"shot_id":1,"character":"SOON YOUNG","line":"I will not have friends in America.","followup":""},{"shot_id":1,"character":"LEE","line":"Soon Young, don't worry. You will  have many friends very soon. You will  see. America is a very friendly  place. ","followup":""}],"key_words":["SOON YOUNG","LEE"]}]}]},{"id":56,"transition":"DISSOLVE TO:","locations":[{"position":"EXT","place":"THE DINER PARKING LOT","time":"NIGHT","shots":[{"id":0,"on":"LOCATION","desc":"We're on JAMES CARTER mid twenties, dressed to impress. It doesn't appear to be working, however, because he has a GUN to his head.","sentences":[{"shot_id":0,"character":"MAN'S VOICE","line":"You don't move, you understand?! You  don't move!","followup":""},{"shot_id":0,"character":"CARTER","line":"Do I look like I'm movin'?! What  you're seeing here? This is not  movement. This is my \"still\". The man who is holding the gun is HENRY LAFONTAINE, thirty, shaved head, expensive clothes. Lafontaine pushes Carter until he's leaning forward on a parked JAGUAR. He starts patting Carter down. With his feet spread apart, hands spread on the trunk, Carter looks like a suspect who is being arrested. Lafontaine starts feeling around Carter's legs, moving higher up.","followup":"He starts patting Carter down. With his feet spread apart, hands spread on the trunk, Carter looks like a suspect who is being arrested. Lafontaine starts feeling around Carter's legs, moving higher up."},{"shot_id":0,"character":"CARTER","line":"Hey, hey, you start touching me there,  I'm gonna start movin'! Word up,  mother... ","followup":""},{"shot_id":0,"character":"LAFONTAINE","line":"(interrupting) Shut up!","followup":""},{"shot_id":0,"character":"CARTER","line":"You a cop or something?","followup":""},{"shot_id":0,"character":"LAFONTAINE","line":"Or somethin'. Lafontaine backs off, pulling the gun away from Carter's head.","followup":""},{"shot_id":0,"character":"LAFONTAINE","line":"I don't trust anybody. Especially  first time deals.","followup":""},{"shot_id":0,"character":"CARTER","line":"I oughta pat your ass down. Make sure  you're not a cop.","followup":""},{"shot_id":0,"character":"LAFONTAINE","line":"Nobody touches me.","followup":""},{"shot_id":0,"character":"CARTER","line":"Shit, I ain't interested in puttin' my  hands on you. That does nothin' for  me. No. I don't need to be patt
